apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: invoice-sqs-scaler
  namespace: shopcloud
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: invoice-consumer
  minReplicaCount: 0
  maxReplicaCount: 5
  triggers:
    - type: aws-sqs-queue
      authenticationRef:
        name: invoice-sqs-trigger-auth
      metadata:
        queueURL: $(SQS_QUEUE_URL)
        queueLength: "5"
        awsRegion: eu-west-1
        scaleOnInFlight: "false"
        identityOwner: pod
