apiVersion: v1
kind: ServiceAccount
metadata:
  name: catalog
  namespace: shopcloud
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::379604374648:role/shopcloud-default-irsa-catalog
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cart
  namespace: shopcloud
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::379604374648:role/shopcloud-default-irsa-cart
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: checkout
  namespace: shopcloud
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::379604374648:role/shopcloud-default-irsa-checkout
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: auth
  namespace: shopcloud
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::379604374648:role/shopcloud-default-irsa-auth
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin
  namespace: shopcloud
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::379604374648:role/shopcloud-default-irsa-admin
